# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 397)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 231, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_car_id = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_car_id.setObjectName("label_car_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_car_id)
        self.lineEdit_car_id = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_car_id.setObjectName("lineEdit_car_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_car_id)
        self.label_team = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_team.setObjectName("label_team")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_team)
        self.lineEdit_team = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_team.setObjectName("lineEdit_team")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_team)
        self.label_route = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_route.setObjectName("label_route")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_route)
        self.lineEdit_route = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_route.setObjectName("lineEdit_route")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_route)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_scrap = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_scrap.setObjectName("le_scrap")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_scrap)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 20, 241, 241))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_updatetime = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_updatetime.setObjectName("label_updatetime")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_updatetime)
        self.lineEdit_updatetime = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_updatetime.setObjectName("lineEdit_updatetime")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_updatetime)
        self.label_busload = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_busload.setObjectName("label_busload")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_busload)
        self.lineEdit_busload = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_busload.setObjectName("lineEdit_busload")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_busload)
        self.label_cartype = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_cartype.setObjectName("label_cartype")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_cartype)
        self.lineEdit_cartype = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_cartype.setObjectName("lineEdit_cartype")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_cartype)
        self.label_carlength = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_carlength.setObjectName("label_carlength")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_carlength)
        self.lineEdit_carlength = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_carlength.setObjectName("lineEdit_carlength")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_carlength)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pbshowImage = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pbshowImage.setObjectName("pbshowImage")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pbshowImage)
        self.formLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 270, 501, 73))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_des = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_des.setObjectName("label_des")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_des)
        self.textEdit_des = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.textEdit_des.setObjectName("textEdit_des")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_des)
        self.pbClose = QtWidgets.QPushButton(Dialog)
        self.pbClose.setGeometry(QtCore.QRect(320, 360, 75, 23))
        self.pbClose.setObjectName("pbClose")
        self.pbEdit = QtWidgets.QPushButton(Dialog)
        self.pbEdit.setGeometry(QtCore.QRect(410, 360, 75, 23))
        self.pbEdit.setObjectName("pbEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "车辆详情"))
        self.label_car_id.setText(_translate("Dialog", "车辆id："))
        self.label_team.setText(_translate("Dialog", "所属车队："))
        self.label_route.setText(_translate("Dialog", "所属线路："))
        self.label_2.setText(_translate("Dialog", "是否报废："))
        self.label_updatetime.setText(_translate("Dialog", "登记时间："))
        self.label_busload.setText(_translate("Dialog", "核定载客："))
        self.label_cartype.setText(_translate("Dialog", "车型："))
        self.label_carlength.setText(_translate("Dialog", "车长："))
        self.label.setText(_translate("Dialog", "行驶证\n"
"扫描件:"))
        self.pbshowImage.setText(_translate("Dialog", "显示"))
        self.label_des.setText(_translate("Dialog", "备注："))
        self.pbClose.setText(_translate("Dialog", "关闭"))
        self.pbEdit.setText(_translate("Dialog", "编辑"))

